### ISSUE TITLE
PodIp not set

### ISSUE THREAD

**Issue by ekozan** [kubernetes-incubator/nfs-provisioner#42]
in kubernetes 1.5.1 pod info ( name ip )  is async so in some case it's set 3 or 5 sec after app start we need to handle this case ( start condition ) 

bug track -> https://github.com/kubernetes/kubernetes/issues/39113

**Comment by wongma7** [comment]
It's an error that we use pod IP in the deployment, statefulset, & daemonset yamls, in reality it isn't  used for anything anymore. I will remove it from those yamls to avoid this issue there.

So this issue will only affect those running the provisioner as a standalone pod. I don't want to do anything to solve this that will affect the other (better & documented) ways of running. Any objections to just waiting for them to fix this bug?

**Comment by ekozan** [comment]
i'm not sure about this one 

I have setup the nfs-provider with DaemonSet and this idiot set the nfs server adresse as my server domain

( kube1.domain.tld ) and not the podIp  it's since I have updated to kube 1.5.1

**Comment by wongma7** [comment]
Can I see the daemonset yaml? I get you should be able to use pod ip if you want to.

I'll work on a proper fix, I realized theres an easy way to do it that works everywhere

**Comment by ekozan** [comment]
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2016-12-25T18:43:47Z
  generation: 1
  labels:
    app: nfs-provisioner
  name: nfs-provisioner
  namespace: default
  resourceVersion: "6059087"
  selfLink: /apis/extensions/v1beta1/namespaces/default/daemonsets/nfs-provisioner
  uid: 122ea6b2-cad2-11e6-853c-7054d216f5a7
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-provisioner
    spec:
      containers:
      - args:
        - -provisioner=eko.ovh/nfs
        - grace-period=0
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: quay.io/kubernetes_incubator/nfs-provisioner:v1.0.1
        imagePullPolicy: IfNotPresent
        name: nfs-provisioner
        ports:
        - containerPort: 2049
          name: nfs
          protocol: TCP
        - containerPort: 20048
          name: mountd
          protocol: TCP
        - containerPort: 111
          name: rpcbind
          protocol: TCP
        - containerPort: 111
          name: rpcbind-udp
          protocol: UDP
        resources: {}
        securityContext:
          capabilities:
            add:
            - DAC_READ_SEARCH
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /export
          name: export-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        app: nfs-provisioner
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /mnt/data
        name: export-volume
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
```

**Comment by ekozan** [comment]
any ide for fix the problem ?

**Comment by wongma7** [comment]
If NODE_NAME is set, the provisioner will use it to set the nfs server ip to the spec.nodeName. which I assume you do not want because then there would be an nfs server from your tld. So if you want it to use the pod IP instead, have to remove this:
```yaml
 - name: NODE_NAME
   valueFrom:
     fieldRef:
       apiVersion: v1
       fieldPath: spec.nodeName
```
Now, the problem with using pod IP you have found is that it isn't set for a few seconds at the beginning, so if it were to try to Provision a PV for a PVC in those few seconds, it would use the output of `hostname -p` instead of the pod IP which is also wrong. Do I understand correctly?

I am working on making it smarter, to not use `hostname -p` except when it's running out of cluster and has no other choice.

**Comment by ekozan** [comment]
okay I got it 👍

**Comment by wongma7** [comment]
OK, this particular issue is fixed by https://github.com/kubernetes-incubator/nfs-provisioner/pull/52 . if pod IP is not set in time, provision will fail and retry a couple seconds later.

So I will have to find a proper place to document this but basically new behavior is:
* if NODE_NAME is set, NFS server IP will be set to the name of the node it's running on
* if SERVICE_NAME is set, POD_IP and POD_NAMESPACE must also be set: if the service is valid, NFS server IP will be set to the cluster IP of the service
* if neither NODE_NAME or SERVICE_NAME is set, NFS server IP will be set to the (potentially unstable) pod IP from POD_IP

if any questions don't hesitate to ask :)
