### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by sands6** [kubernetes-incubator/nfs-provisioner#69]
Please advise if there is a issue with nfs-provisioner image. I have pulled v1.0.3 and below is the error log and I used deployment.yaml method. 

E0119 22:22:43.974082       1 reflector.go:199] github.com/kubernetes-incubator/nfs-provisioner/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.PersistentVolumeClaim: an error on the server ("Internal Server Error: \"/api/v1/persistentvolumeclaims?resourceVersion=0\"") has prevented the request from succeeding (get persistentvolumeclaims)
E0119 22:22:43.975106       1 reflector.go:199] github.com/kubernetes-incubator/nfs-provisioner/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1beta1.StorageClass: an error on the server ("Internal Server Error: \"/apis/storage.k8s.io/v1beta1/storageclasses?resourceVersion=0\"") has prevented the request from succeeding (get storageclasses.storage.k8s.io)

**Comment by wongma7** [comment]
What is the output of `kubectl version`? You can do `kubectl get persistentvolumeclaims` fine, right?

**Comment by sands6** [comment]
Here is the version. I try to deploy the nfs-provisioner and check the logs on the container. I see the above errors. When I try to create a claim, it stays in pending state, complaining about no available volumes to use.

But the fact is the storage class and nfs-provsioner are deployed already. But checking against nfs-provisioner container logs points me the provisioner is not deployed completely for unknown reason.
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommi
t:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2
016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"windows/amd6
4"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1+coreos.0",
 GitCommit:"cc65f5321f9230bf9a3fa171155c1213d6e3480e", GitTreeState:"clean", Bui
ldDate:"2016-12-14T04:08:28Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"lin
ux/amd64"}

**Comment by wongma7** [comment]
Can you please provide your Kubernetes apiserver.log around the time these errors happen? Are you using other apps like dashboard or heapster without issue? Perhaps this is an authentication problem, do you have ABAC enabled or have you done any sort of configuration with service accounts?

The pod has deployed fine, it was able to initially communicate with the apiserver to get the server version. But I don't know what "internal server error" could mean, the request looks fine to me & usually Kubernetes handles all this communication automatically. So please bear with me :)

**Comment by sands6** [comment]
Is this a problem? the below logs are from api-server pod

E0120 20:55:40.920797       1 errors.go:42] clusterrole.rbac.authorization.k8s.i
o "services-reader" not found
E0120 20:55:41.956493       1 errors.go:42] clusterrole.rbac.authorization.k8s.i
o "services-reader" not found
E0120 20:55:42.987576       1 errors.go:42] clusterrole.rbac.authorization.k8s.i
o "services-reader" not found
E0120 20:55:44.014179       1 errors.go:42] clusterrole.rbac.authorization.k8s.i
o "services-reader" not found
E0120 20:55:45.042536       1 errors.go:42] clusterrole.rbac.authorization.k8s.i
o "services-reader" not found
E0120 20:55:46.067160       1 errors.go:42] clusterrole.rbac.authorization.k8s.i
o "services-reader" not found

**Comment by wongma7** [comment]
This means your cluster has [RBAC](https://kubernetes.io/docs/admin/authorization/) enabled, you can make sure by checking what flags apiserver was started with. I guess what this apiserver error means is that there's a `ClusterRoleBinding` referring to a non-existent "services-reader" `ClusterRole`. Do the logs show anything else about RBAC?

With RBAC enabled the nfs-provisioner pod won't work unless it (the user running it) has been granted some needed permissions. So I guess the "internal server" errors you got are because RBAC denied these needed permissions.

These are the permissions it needs: 
"get", "list", "watch", "create", "delete" `PersistentVolumes`
"get", "list", "watch", "update" `PersistentVolumeClaims`
"get", "list", "watch" `StorageClasses`
"get" `Services`
"create", "update", "patch" `Events`

I will properly document this with instructions on how to create a ClusterRole & ClusterRoleBinding next week.

I'll also try to get a bootstrap `ClusterRole` for provisioners into kube 1.6 so it won't be so hard.

**Comment by sands6** [comment]
Thank you. I will trying setting these permissions and get back to you.

**Comment by wongma7** [comment]
I missed one: "get" `Endpoints`.

Still working on proper docs, I am new to RBAC myself.

**Comment by wongma7** [comment]
It was only a guess that this issue is caused by RBAC so if not please reopen.
